// packages/table-grid-vue/src/components/body/rows.vue
<template>
  <BodyRow v-for="rowData in rowDataSource" :key="rowData.rowKey" :row-key="rowData.rowKey" :meta="rowData.meta"
    :index="rowData.meta?.index ?? -1" :record="rowData.record" :columns="computedColumns" :grid="grid"
    :prefix-cls="prefixCls" />
</template>

<script lang="ts" setup>
import type { ColKey, RawData } from "@scode/table-grid-core";
import BodyRow from "./row.vue";
import { useStateInject } from "../../hooks";
import { computed } from "vue";

interface BodyRowsProps {
  prefixCls: string;

  dataSource: RawData[];

  colKeys: ColKey[];

  grid: number[];

  isNestDataSource: boolean;
}

const props = defineProps<BodyRowsProps>();

const { tableState, mapToColumn } = useStateInject();

const getRowKey = tableState.config.get_row_key;
const rowState = tableState.get_row_state();

const computedColumns = computed(() => {
  return props.colKeys.map(colKey => {
    return {
      colKey,
      column: mapToColumn(colKey)
    }
  })
})


const rowDataSource = computed(() => {
  return (props.dataSource ?? []).map((rawData) => {
    const rowKey = getRowKey(rawData);
    const rowMeta = rowState.get_meta_by_row_key(rowKey);

    return {
      rowKey,
      meta: rowMeta,
      record: rawData
    }
  });
});

</script>

// packages/table-grid-react/src/components/body/rows.tsx
import type { ColKey, RawData } from "@scode/table-grid-core";
import BodyRow from "./row";
import { useContext } from "react";
import { StateContext } from "../context";

interface BodyRowsProps {
  prefixCls: string;

  dataSource: RawData[];

  colKeys: ColKey[];

  grid: number[];

  isNestDataSource?: boolean;
}


export default function (props: BodyRowsProps) {
  const { dataSource, colKeys, grid, prefixCls } = props;
  const { tableState, mapToColumn } = useContext(StateContext);

  const getRowKey = tableState.config.get_row_key;
  const rowState = tableState.get_row_state();

  const columns = colKeys.map(colKey => {
    return {
      colKey,
      column: mapToColumn(colKey)
    }
  });

  function renderRow(record: RawData) {
    const rowKey = getRowKey(record);
    const rowMeta = rowState.get_meta_by_row_key(rowKey);
    return <BodyRow prefixCls={prefixCls} key={rowKey} rowKey={rowKey} meta={rowMeta} index={rowMeta?.index ?? -1} record={record} columns={columns} grid={grid}></BodyRow>
  }

  return (
    <>
      {dataSource.map(record => renderRow(record))}
    </>
  );
}
