// packages/table-grid-vue/src/Table.vue
<template>
  <div ref="tableRef" :class="tableClass">
    <InternalTable ref="internalTable" v-bind="props"></InternalTable>
  </div>
</template>

<script lang="ts" setup>
import type { TableProps, InternalTableRef, TableEmit } from "./typing";
import { useStateProvide } from "./hooks";
import InternalTable from "./components/InternalTable.vue";
import { shallowRef, computed, watch } from "vue";

defineOptions({
  name: "STable",
});

const props = withDefaults(defineProps<TableProps>(), {
  prefixCls: "s-table",
  bordered: false,
  rowChildrenName: "children",
});

const emit = defineEmits<TableEmit>()

const { tableRef, tableState, updateColumns } = useStateProvide(props);

watch(() => props.columns, () => {
  updateColumns(props.columns ?? []);
}, { immediate: true });

watch(() => props.dataSource, () => {
  tableState.value.update_dataset(props.dataSource ?? [])
}, { immediate: true });

const internalTable = shallowRef<InternalTableRef>();

const tableClass = computed(() => [props.prefixCls]);
</script>

// packages/table-grid-react/src/Table.tsx
import type { TableProps } from "./typing";
import { useRef, type CSSProperties } from "react";
import { InternalTable } from "./components/InternalTable";
import { StateContext } from "./components/context";


const DefaultTableProps: TableProps = {
  prefixCls: 's-table',
  bordered: false,
  rowChildrenName: "children"
};

export function Table(props: TableProps & { style?: CSSProperties }) {
  const { style, ...rest } = Object.assign({}, props, DefaultTableProps);

  const tableClass = [rest.prefixCls!].join(' ');

  const tableRef = useRef<HTMLDivElement>(null);

  // 看看未来这个这么支持
  const internalTable = useRef(null);

  return (
    <div ref={tableRef} className={tableClass} style={style}>
      {/* TODO: 需要整合逻辑到这里 */}
      <StateContext.Provider value={{} as any}>
        <InternalTable {...rest} ></InternalTable>
      </StateContext.Provider>
    </div>
  )
}
