// packages/table-grid-vue/src/components/header/cell.vue
<script lang="ts">
import type { TableHeaderCellProps } from "./typing";
import type { StyleValue, VNode } from 'vue';
import { h, defineComponent } from 'vue';
import ResizeHolder from "./ResizeHolder.vue";
import type { TableColumn } from "../../typing";

// 渲染用户配置的 title
function renderColumnTitle(column: TableColumn) {
  return typeof column.title === "function"
    ? column.title()
    : column.title;
}

export default defineComponent<TableHeaderCellProps>({
  name: "STableHeaderCell",

  props: ["prefixCls", "colKey", "column", "ellipsis"],

  setup(props) {
    const cellPrefixClass = props.prefixCls + "-cell";

    function renderHeaderCell(column: TableColumn) {
      const title = renderColumnTitle(column);

      const appendVNodes: VNode[] = [];

      // 渲染排序

      // 渲染筛选

      if (appendVNodes.length) {
        const appendWrapper = h("div", { class: cellPrefixClass + "__append" }, appendVNodes);

        return h("div", { class: cellPrefixClass + "__append" }, [
          title,
          appendWrapper,
        ] as any[]);
      }

      return title;
    }

    return () => {
      const { ellipsis, column } = props;

      const cell = renderHeaderCell(column);

      const title = ellipsis?.showTitle ? cell : undefined;

      // 单元格内部
      const cellInnerClass = {
        [`${cellPrefixClass}-inner`]: true,
        [`${cellPrefixClass}-inner-ellipsis`]: !!ellipsis
      };
      const cellInnerStyle: StyleValue = {
        textAlign: column.align
      };

      const inner = h('div', { class: cellInnerClass, style: cellInnerStyle }, [
        cell,
      ] as any[]);

      // 列宽调整 holder
      const resizeHolder = column.resizable ? h(ResizeHolder) : null;

      // 单元格
      const cellClass = [cellPrefixClass];
      return h('div', { class: cellClass, title }, [
        inner,
        resizeHolder
      ])

    }
  }
});
</script>

// packages/table-grid-react/src/components/header/cell.tsx
import type { TableHeaderCellProps } from "./typing";
import type { CSSProperties } from "react";
import { useRef } from "react";
import classNames from "classnames";
import ResizeHolder from "./ResizeHolder";

export default function (props: TableHeaderCellProps) {
  const { prefixCls, colKey, column, width, ellipsis } = props;

  const cellPrefixCls = prefixCls + "-cell";

  const cellRef = useRef<HTMLDivElement>(null);
  const cellClass = classNames({
    [cellPrefixCls]: true,
    // TODO:
  });
  const cellStyle: CSSProperties = {};

  // 表格内部
  const cellInnerRef = useRef<HTMLDivElement>(null);
  const cellInnerClass = classNames({});

  // FIXME:
  const text = column.title;
  // 列宽调整 holder
  const resizeHolder = column.resizable ? <ResizeHolder prefixCls={cellPrefixCls} colKey={colKey}></ResizeHolder> : null;

  return (
    <div ref={cellRef} className={cellClass} style={cellStyle}>
      <div ref={cellInnerRef} className={cellInnerClass}>
        <>
          {text}
          {resizeHolder}
        </>
      </div>
    </div>
  )
}
