// packages/table-grid-vue/src/components/header/index.vue
<template>
  <div ref="tableHeaderRef" :class="tableHeaderClass" :style="tableHeaderStyle">
    <div :class="prefixCls + '__inner'">
      <div v-if="leftColumnsVisible" ref="tableHeaderLeftRef" :class="leftColumnsClass" :style="leftColumnsStyle">
        <HeaderCells :prefix-cls="prefixCls" :col-keys="tableState.last_left_col_keys"
          :flatten-col-keys="tableState.left_col_keys" :map-to-column="mapToColumn">
        </HeaderCells>
      </div>

      <div ref="tableHeaderCenterRef" :class="centerColumnsClass" :style="centerColumnsStyle">
        <HeaderCells :prefix-cls="prefixCls" :col-keys="tableState.last_center_col_keys"
          :flatten-col-keys="tableState.center_col_keys" :map-to-column="mapToColumn" type="center">
        </HeaderCells>
      </div>

      <div v-if="rightColumnsVisible" ref="tableHeaderRightRef" :class="rightColumnsClass" :style="rightColumnsStyle">
        <HeaderCells :prefix-cls="prefixCls" :col-keys="tableState.last_right_col_keys"
          :flatten-col-keys="tableState.right_col_keys" :map-to-column="mapToColumn">
        </HeaderCells>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { StyleValue } from "vue";
import type { TableHeaderProps } from "./typing";

import { useStateInject } from "../../hooks";
import { computed, shallowRef } from 'vue';
import HeaderCells from "./cells.vue";

const props = defineProps<TableHeaderProps>()

const { tableState, tableProps, mapToColumn } = useStateInject();

// 表头
const tableHeaderRef = shallowRef<HTMLElement>();
const tableHeaderClass = computed(() => {
  const { prefixCls } = props;
  return [prefixCls];
});
const tableHeaderStyle = computed<StyleValue>(() => {
  return {};
});

// 左侧表头
const tableHeaderLeftRef = shallowRef<HTMLElement>();
const leftColumnsVisible = computed(() => {
  const { last_left_col_keys = [] } = tableState.value || {};
  return !!last_left_col_keys.length;
});
const leftColumnsClass = computed(() => {
  const { prefixCls } = props;
  const { prefixCls: _prefixCls} = tableProps;
  return {
    [`${_prefixCls}-fixedLeft`]: true,
    [`${prefixCls}__inner-fixedLeft`]: true,
    shadow: tableState.value.scroll.left > 0
  };
});
const leftColumnsStyle = computed<StyleValue>(() => {
  const style: StyleValue = {};
  const colState = tableState.value.get_col_state()

  const deepest = colState.get_deepest() + 1;

  const { last_left_col_keys, config } = tableState.value;

  style.gridTemplateRows = "repeat(" + deepest + ", 52px)";
  style.gridTemplateColumns = last_left_col_keys
    .map(colKey => {
      return (colState.get_meta(colKey)?.width ?? config.col_width) + 'px';
    })
    .join(' ');

  return style;
});

// 中间表头
const tableHeaderCenterRef = shallowRef<HTMLElement>();
const centerColumnsClass = computed(() => {
  const { prefixCls } = props;
  return {
    [`${prefixCls}__inner-center`]: true
  };
});
const centerColumnsStyle = computed<StyleValue>(() => {
  const style: StyleValue = {};
  const colState = tableState.value.get_col_state()

  const deepest = colState.get_deepest() + 1;

  const { last_left_col_keys, last_center_col_keys, config ,scroll} = tableState.value;

  style.paddingLeft = colState.get_reduce_width(last_left_col_keys) +'px';
  style.gridTemplateRows = "repeat(" + deepest + ", 52px)";
  style.transform = `translateX(${-scroll.left}px)`
  style.gridTemplateColumns = last_center_col_keys
    .map(colKey => {
      return (colState.get_meta(colKey)?.width ?? config.col_width) + 'px';
    })
    .join(' ');

  return style;
});

// 右侧表头
const tableHeaderRightRef = shallowRef<HTMLElement>();
const rightColumnsVisible = computed(() => !!tableState.value.last_right_col_keys.length);
const rightColumnsClass = computed(() => []);
const rightColumnsStyle = computed<StyleValue>(() => {
  return {}
});
</script>

// packages/table-grid-react/src/components/header/index.tsx
import { useContext, useRef, type CSSProperties } from "react";
import type { TableHeaderProps } from "./typing";
import classNames from "classnames";
import { StateContext } from "../context";
import HeaderCells from "./cells";

export function TableHeader(props: TableHeaderProps) {
  const { prefixCls } = props;

  const { tableState, tableProps, mapToColumn } = useContext(StateContext);

  const tableHeaderRef = useRef<HTMLDivElement>(null);
  const tableHeaderClass = classNames({
    [prefixCls]: true,
  });

  const { last_center_col_keys, last_left_col_keys, last_right_col_keys, config } = tableState;

  const colState = tableState.get_col_state();

  const tableHeaderStyle = {};

  // 表格中间
  const tableHeaderCenterRef = useRef<HTMLDivElement>(null);
  const centerColumnsClass = classNames({
    [`${prefixCls}__inner-center`]: true
  });
  const centerColumnsStyle = (() => {
    const deepest = colState.get_deepest() + 1;
    const { last_center_col_keys, config } = tableState;

    const style: CSSProperties = {};
    style.paddingLeft = colState.get_reduce_width(last_left_col_keys) + 'px';
    style.gridTemplateRows = "repeat(" + deepest + ", 52px)";
    style.gridTemplateColumns = last_center_col_keys
      .map(colKey => {
        return (colState.get_meta(colKey)?.width ?? config.col_width) + 'px';
      })
      .join(' ');

    return style;
  })();

  let fixedLeftHeader = null;

  if (last_left_col_keys.length) {
    const leftColumnsClass = classNames({
      [`${tableProps.prefixCls}-fixedLeft`]: true,
      [`${prefixCls}__inner-fixedLeft`]: true,
      // shadow: tableState.value.scroll.left > 0
    })

    const leftColumnsStyle = (() => {
      const deepest = colState.get_deepest() + 1;
      return {
        gridTemplateRows: "repeat(" + deepest + ", 52px)",
        gridTemplateColumns: last_left_col_keys
          .map(colKey => {
            return (colState.get_meta(colKey)?.width ?? config.col_width) + 'px';
          })
          .join(' ')
      };
    })();
    fixedLeftHeader = (
      <div className={leftColumnsClass} style={leftColumnsStyle}>
        <HeaderCells prefixCls={prefixCls} colKeys={last_left_col_keys} flattenColKeys={tableState.left_col_keys} mapToColumn={mapToColumn}></HeaderCells>
      </div>
    )
  }

  return (
    <div ref={tableHeaderRef} className={tableHeaderClass} style={tableHeaderStyle}>
      <div className={prefixCls + '__inner'}>

        {fixedLeftHeader}

        <div ref={tableHeaderCenterRef} className={centerColumnsClass} style={centerColumnsStyle}>
          <HeaderCells prefixCls={prefixCls} colKeys={tableState.last_center_col_keys} flattenColKeys={tableState.center_col_keys} mapToColumn={mapToColumn}></HeaderCells>
        </div>
      </div>
    </div>
  )
}
